apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6c7i
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-6c7i@sha256:d026fdb5e74f33e299c47eaf6909d06e8903379de5d17db76865de3adcb35a9b
        name: my-nodejs
        resources: {}
status: {}
